image = "nvcr.io/nvidia/jax:26.01-py3"

mounts = ["/capstor", "/iopsstor", "/users"]
workdir = "/users/alexpadula/projects/ludax"

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"