# python examples/03-alpha-zero/train.py env_id=reversi     env_type=ldx     seed=0     max_num_iters=400     num_channels=64     num_layers=4     resnet_v2=True     selfplay_batch_size=4096     num_simulations=32     max_num_steps=64     training_batch_size=4096     learning_rate=0.001     eval_interval=10     eval_num_games=128  ckpt_dir="/users/alexpadula/store/ludax/checkpoints/reversi"
python examples/03-alpha-zero/train.py env_id=reversi     env_type=pgx     seed=0     max_num_iters=400     num_channels=64     num_layers=4     resnet_v2=True     selfplay_batch_size=4096     num_simulations=32     max_num_steps=64     training_batch_size=4096     learning_rate=0.001     eval_interval=10     eval_num_games=128  ckpt_dir="/users/alexpadula/store/ludax/checkpoints/reversi"
python examples/03-alpha-zero/train.py env_id=reversi     env_type=ldx     seed=1     max_num_iters=400     num_channels=64     num_layers=4     resnet_v2=True     selfplay_batch_size=4096     num_simulations=32     max_num_steps=64     training_batch_size=4096     learning_rate=0.001     eval_interval=10     eval_num_games=128  ckpt_dir="/users/alexpadula/store/ludax/checkpoints/reversi"
python examples/03-alpha-zero/train.py env_id=reversi     env_type=pgx     seed=1     max_num_iters=400     num_channels=64     num_layers=4     resnet_v2=True     selfplay_batch_size=4096     num_simulations=32     max_num_steps=64     training_batch_size=4096     learning_rate=0.001     eval_interval=10     eval_num_games=128  ckpt_dir="/users/alexpadula/store/ludax/checkpoints/reversi"
python examples/03-alpha-zero/train.py env_id=reversi     env_type=ldx     seed=2     max_num_iters=400     num_channels=64     num_layers=4     resnet_v2=True     selfplay_batch_size=4096     num_simulations=32     max_num_steps=64     training_batch_size=4096     learning_rate=0.001     eval_interval=10     eval_num_games=128  ckpt_dir="/users/alexpadula/store/ludax/checkpoints/reversi"
python examples/03-alpha-zero/train.py env_id=reversi     env_type=pgx     seed=2     max_num_iters=400     num_channels=64     num_layers=4     resnet_v2=True     selfplay_batch_size=4096     num_simulations=32     max_num_steps=64     training_batch_size=4096     learning_rate=0.001     eval_interval=10     eval_num_games=128  ckpt_dir="/users/alexpadula/store/ludax/checkpoints/reversi"
python examples/03-alpha-zero/train.py env_id=reversi     env_type=ldx     seed=3     max_num_iters=400     num_channels=64     num_layers=4     resnet_v2=True     selfplay_batch_size=4096     num_simulations=32     max_num_steps=64     training_batch_size=4096     learning_rate=0.001     eval_interval=10     eval_num_games=128  ckpt_dir="/users/alexpadula/store/ludax/checkpoints/reversi"
python examples/03-alpha-zero/train.py env_id=reversi     env_type=pgx     seed=3     max_num_iters=400     num_channels=64     num_layers=4     resnet_v2=True     selfplay_batch_size=4096     num_simulations=32     max_num_steps=64     training_batch_size=4096     learning_rate=0.001     eval_interval=10     eval_num_games=128  ckpt_dir="/users/alexpadula/store/ludax/checkpoints/reversi"

python examples/03-alpha-zero/tournament.py --env_id reversi --env_type pgx --games_per_pair 64 --log_interval 100 --output_path examples/05-paper-figures/data/rl_runs/elo_reversi.pkl --dirs /users/alexpadula/store/ludax/checkpoints/reversi/*
